### ISSUE TITLE
plugins initialization failed (nofunction loaded) when running user.py

### ISSUE THREAD

**Issue by Afzal6991** [wajdan846/Openbci-Raspberry-pi-2-Beta-interfacing-Signal-Processing-and-Realtime-Plotting#1]
after running user.py script ,when i add the plugins like by typing add print, i get message" initialization failed ,could not find Fat16/32 partition".i have every thing alright ,Sdcard is inserted and format is fat 32.
i am running this on Raspbian OS at Raspberry pie 3.python version is 2.7.i haive plugged in usb dongle of openbci in rasppberry pie 3,to get eeg live data into my raspberrypie.

i have attached the snapshot below.
errors
![image](https://user-images.githubusercontent.com/15672665/38405538-d75e3704-3989-11e8-9297-f619fb9a737a.png)

**Comment by Afzal6991** [comment]
i was using python idle to run code ,however running the code from linux terminal using sudo user.py add plugin the error was resolved

**Comment by wajdan846** [comment]
run test.py for retrieving data initially from the openBCI , here you can add your custom code in the callback function that is directly being accessed from openbciV3.py library by maintaining a serial interface with the openbci. 
**Note:** Here the data is not being saved in the csv format, instead you are free to store data sample by sample in , lets say dynamic arrays and perform pre and post processing etc.
